### ISSUE TITLE
"Routines" should be "Abläufe" in german

### ISSUE THREAD

**Issue by zreptil** [nielsmaerten/nightscout-assistant#105]
**Describe the bug**
On the page "https://nielsmaerten.github.io/nightscout-assistant" there is the dialog "settings saved". It says in the german version as a tip that "Routinen" could be used to make it easier to access. "Routines" is called "Abläufe" in german by Google. Clicking on "Routinen" brings up the english help site of google nest help. I think it would be better, if it was the version of the site in the same language that was selected on the combobox.

**To Reproduce**
1. Go to 'https://nielsmaerten.github.io/nightscout-assistant'
2. Click on 'English'
3. Change to 'Deutsch'
3. Enter a valid entry in 'Deine Nightscout Seite'
4. Click on 'Speichern'
5. See "Routinen" on dialog

**Expected behavior**
It should say "Abläufe" in german and the link should lead to the german version of the google help page.

**Platform (please complete the following information where applicable):**
 - Browser Chrome

**Comment by nielsmaerten** [comment]
Thank you for pointing this out.  
I've updated the string in the German locale file, and made the link point to the localized page.

PS: Kudos for your work on Nightscout Reporter! I use it all the time :)

**Comment by zreptil** [comment]
Thanks for the Kudos for NR :) I am very happy, when it is useful.

And thanks for the good work. I tried to activat google home myself, but failed. Your site is great :) Thanks for making Google Home aware of my glucose level :)
