### ISSUE TITLE
Change voice

### ISSUE THREAD

**Issue by robertherber** [nielsmaerten/nightscout-assistant#113]
I find the voice of the Nightscout Action hard to hear in contrast to the ordinary Google Assistant voice. Would it be possible to make the Nightscout Action use the same voice as Google Assistant or at least make it configurable somehow?

**Comment by nielsmaerten** [comment]
Unfortunately not. Google forces other Actions to have a voice that's different from the official Assistant's voice. This is to make it more difficult for malicious actions to impersonate the Assistant.  
If any Action can sound exactly the same as Google, you can probably see how some evil developer could trick some users into revealing their password...

That being said... we may actually experiment with new voices in [Gluco Check](https://github.com/nielsmaerten/gluco-check), which will be the successor to Nightscout Status. I suggest following development in that repository :)
