### ISSUE TITLE
Add new locale: German

### ISSUE THREAD

**Issue by nielsmaerten** [nielsmaerten/nightscout-assistant#33]
## Translations
- [x] New translations approved on Crowdin
- [x] Translations merged into _master_ and _www_ branch
- [x] If Routines are supported, locale code added to `lngsSupportingRoutines` array
- [x] _www_ branch deployed to GitHub Pages
- [x] Translator credit added to README / package.json

## Google Review requirements
- [x] [Prepare for deployment - Google's Checklist](https://developers.google.com/actions/distribute/#prepare_for_deployment)

**Highlights:**
- [x] Privacy policy fully translated
- [x] Display name and Invocation consistent across site, Action and Directory info
- [x] Directory information up-to-date
- [x] Testing instructions up-to-date

## Testing
- [x] Invocation works in the new language
- [x] Tested on real device in alpha

## General deployment
- [x] _master_ branch deployed to Firebase
- [x] Dialogflow fullfilment url pointing to Firebase Function

**Comment by nielsmaerten** [comment]
Updated action has been submitted to Google for review.

**Comment by nielsmaerten** [comment]
German is now available for testing in alpha.
Click this link (on a mobile device) to opt-in to the alpha-version:
https://assistant.google.com/services/a/uid/000000513a29198a?hl=de
You can opt-out anytime.

Once we've confirmed everything is working IRL, we can release the new locale to everyone 👍

**Comment by JonnyJohnson** [comment]
Is the url broken?

**Comment by nielsmaerten** [comment]
Hi @JonnyJohnson 
The URL is fine, but we found there's a catch: I have to add your email address to the list of testers before you can sign up. Just send me a message (hello@niels.me), and I'll get you set up

Thanks for your help!

**Comment by nielsmaerten** [comment]
@JonnyJohnson 
The German version is now live!
Took forever, but we got there in the end :)
