### ISSUE TITLE
Extend to all English-speaking locales

### ISSUE THREAD

**Issue by nielsmaerten** [nielsmaerten/nightscout-assistant#37]
**Is your feature request related to a problem? Please describe.**
Currently, Nightscout Status works in English, but only when the user device is set to English US.

**Describe the solution you'd like**
The goal is to extend availability to _all_ English speaking locales. (Canada, Australia, ...)

**Describe alternatives you've considered**
People in those locales can set their device to US English for the time being.

**Additional context**
The Action has been updated to work in Canada, Australia, India, UK.  
The change is currently being reviewed by Google.  
Barring any legal issues, the Action will be extended to these locales within a few days.
This issue will be updated with any progress.

**Comment by nielsmaerten** [comment]
Updated Dialogflow to serve all English locales. Currently pending review. If approved, Nightscout Status will be available in all English locales within a few days.

**Comment by old-square-eyes** [comment]
@nielsmaerten didn't raise an issue, but NZ English still fails. Did you mean review at Google?

**Comment by nielsmaerten** [comment]
U oh, I was clearly overly optimistic when I estimated this would only take "a few days" 😳

But to answer your question: yes, Google has to approve every Action created for the Assistant.
And it turns out publishing an Acton like this (because it deals with medial information) comes with a whole lot of hoops to jump through.

Publishing was a breeze for US and Sweden, but getting approval for other countries is still a work in progress.

**Comment by nielsmaerten** [comment]
I've been digging around a bit, and I found out that Google Assistant is (for some unknown reason) not available in NZ English :/
From Google's developer docs, here's is the list of (Englis)h locales that are supported:
https://developers.google.com/assistant/console/languages-locales#english_1

Nightscout Status has now been cleared for 9 different languages, including 'generic' English. 
So whenever Google decides to add NZ English to that list, it should become available.

For now, I'm afraid the only workaround I have is setting your device to one of these locales:  
`en-AU`, `en-CA`, `en-GB`, `en-IN`, `en-BE`, `en-SG` or `en-US`
