### ISSUE TITLE
Add new locale: Spanish

### ISSUE THREAD

**Issue by davmartes** [nielsmaerten/nightscout-assistant#44]
## Translations
- [x] New translations approved on Crowdin
- [x] Translations merged into _master_ and _www_ branch
- [x] If Routines are supported, locale code added to `lngsSupportingRoutines` array
- [x] _www_ branch deployed to GitHub Pages
- [x] Translator credit added to README / package.json

## Google Review requirements
- [x] [Prepare for deployment - Google's Checklist](https://developers.google.com/actions/distribute/#prepare_for_deployment)

**Highlights:**
- [x] Privacy policy fully translated
- [x] Display name and Invocation consistent across site, Action and Directory info
- [x] Directory information up-to-date
- [x] Testing instructions up-to-date

## Testing
- [x] Invocation works in the new language
- [x] Tested on real device in alpha

## General deployment
- [x] _master_ branch deployed to Firebase
- [x] Dialogflow fullfilment url pointing to Firebase Function

**Comment by davmartes** [comment]
100% of Spanish translation has been done ion Crowdin. Can they be deployed to be available?

**Comment by nielsmaerten** [comment]
Thank you for this! 
I'll integrate your translation ASAP. 
After that, the action will need to be reviewed and approved by Google before it becomes available in Spanish locales. This usually takes a couple workdays, so I'll keep this issue posted on progress.

**Comment by nielsmaerten** [comment]
Spanish is now available for testing in alpha. 
Click this link (on a mobile device) to opt-in to the alpha-version: 
https://assistant.google.com/services/a/uid/000000513a29198a?hl=es
You can opt-out anytime. 

Once we've confirmed everything is working IRL, we can release the new locale to everyone 👍

**Comment by davmartes** [comment]
I’ve tried to test the alpha version but the link doesn’t seems to work. I’ve sent you a private message on Gitter to be able to give you my google account mail for you to set it up for me. Thanks

**Comment by davmartes** [comment]
Alpha version tested and it works fine

**Comment by nielsmaerten** [comment]
@davmartes 
It took a very looong time, but the Spanish version has been approved!
Should be live now :)
