### ISSUE TITLE
Enhancement to glucose change description

### ISSUE THREAD

**Issue by mistermintsgh** [nielsmaerten/nightscout-assistant#59]
I love this! I've wanted to have my Google Home Mini read my glucose since I first got Nightscout, Libre and so on.

Would it be possible to make a small (I hope!) change to the way the Assistant talks about the glucose change? At the moment it will only tell you if you are rising, steady, or falling. Could 2 further descriptions be added to that? - rising rapidly, falling rapidly

I think this would allow for a much better idea of what is going on when you ask the Assistant.

**Comment by nielsmaerten** [comment]
Hi! Sorry it took me over a week to get back to you (been on holiday ;)

The app is actually doing this already:
Check out [this line of code](https://github.com/nielsmaerten/nightscout-assistant/blob/master/functions/i18n/languages/en.json#L20) and you'll see that the Assistant will say a different trend 
depending on the arrow shown in Nightscout

- 2 up arrows: "Rising fast"
- Single up arrow: "Rising"
- 45° up arrow: "Rising slowly"
- Flat arrow: "Stable"
- 45° down arrow: "Decreasing slowly"
- Single down arrow: "Decreasing"
- 2 down arrows: "Dropping fast"

**And now a big disclaimer: English isn't my first language** 😄 
So maybe the words I've chosen aren't the best way of describing what's happening?
I'd be happy to change it to a better suggestion though

**Comment by mistermintsgh** [comment]
Thank you @nielsmaerten 

I need to do some more testing on mine then, as I don't remember hearing anything other that rising, stable and decreasing. 

I think getting the perfect wording is going to be tough due to local differences in language - my personal preference (as a native English speaker from the UK) would be to substitute "decreasing" for "falling" but appreciate that may not make sense for others. I would probably also change the word "fast" for "rapidly".

Perhaps it may be useful, as an option if people don't want it by default, to also include the change to give a little more context to the information.
For example "6.2 and stable as of 2 minutes ago. Change of minus 0.2 since previous reading" or "8.6 and rising slowly as of 3 minutes ago. Change of plus 0.4 since previous reading"
