### ISSUE TITLE
Add new locale: French

### ISSUE THREAD

**Issue by nielsmaerten** [nielsmaerten/nightscout-assistant#67]
## Translations
- [x] New translations approved on Crowdin
- [x] Translations merged into _master_ and _www_ branch
- [x] If Routines are supported, locale code added to `lngsSupportingRoutines` array
- [x] _www_ branch deployed to GitHub Pages
- [x] Translator credit added to README / package.json

## Google Review requirements
- [x] [Prepare for deployment - Google's Checklist](https://developers.google.com/actions/distribute/#prepare_for_deployment)

**Highlights:**
- [x] Privacy policy fully translated
- [x] Display name and Invocation consistent across site, Action and Directory info
- [x] Directory information up-to-date
- [x] Testing instructions up-to-date

## Testing
- [ ] Invocation works in the new language
- [ ] Tested on real device in alpha

## General deployment
- [x] _master_ branch deployed to Firebase
- [x] Dialogflow fullfilment url pointing to Firebase Function

**Comment by ErwynLein** [comment]
Where are we with the french translation ? I have seen that it was included on the site, but I don't think it work yet ?

**Comment by nielsmaerten** [comment]
Hi @ErwynLein . The translation is done and has been integrated into the code.
But Google needs to review each new version of the app before it can be rolled out.
Unfortunately, this seems to take a very long time.

The latest version has been under review for over 2 weeks now, so I hope it'll be approved soon. 
Once approved, the app will be available in French, Spanish, Polish, Danish, Dutch, Swedish, Italian and German

If you want, I can add you to the list of alpha testers. That'll give you early-access to the French version. Just send me an email (hello@niels.me) if you'd like that

**Comment by ErwynLein** [comment]
I've sent you an email about that ! Maybe do you need my gmail adress in the mail... ?

**Comment by nielsmaerten** [comment]
@ErwynLein Correct :) It needs to be the email address you use with your Google Account

**Comment by nielsmaerten** [comment]
@ErwynLein 
It took a very long time, but Google has now approved the French version :)
Should be live!
