### ISSUE TITLE
No longer working on Google Home Mini

### ISSUE THREAD

**Issue by mistermintsgh** [nielsmaerten/nightscout-assistant#72]
**Describe the bug**
I haven't changed any settings, but since the Google Pixel launch (and that of the new Nest speaker and therefore probably a firmware update) this hasn't been working. I've tried my routine commands, and the default "Hey Google, talk to Nightscout status" but I get the response "Sorry, I don't know how to help with that".

I've checked that everything is still connected on the "sign up" page for NS Assistant, and it all looks normal.

**To Reproduce**
1. Say "Hey Google, check my sugar/talk to Nightscout status"
2. "Google responds "Sorry, I don't know how to help with that"

**Expected behavior**
A reading of my current BG level and how it is changing (e.g. "6.5 and steady as of 2 minutes ago")

**Screenshots**

**Platform (please complete the following information where applicable):**
 - OS: Android 9
 - Device: Home Mini, Samsung S10+

**Additional context**

**Comment by nielsmaerten** [comment]
Thanks for alerting me!  
Looks like Google messed up big time and undeployed the app during the last round of reviews. o_o
I'm doing my best to get it redeployed ASAP

**Comment by mistermintsgh** [comment]
Thanks @nielsmaerten Fingers crossed you get it resolved soon! Good luck!

**Comment by nielsmaerten** [comment]
Tiny update: 

Still haven't heard back from Google 😞 
I can't redeploy the app myself, so we'll have to wait for them to do it.
I'm really sorry. This sucks!

**Comment by ThaDoc** [comment]
https://voicebot.ai/2019/10/18/thousands-of-google-actions-mysteriously-disappeared-from-online-directory-and-are-no-longer-available-google-says-it-could-take-weeks-to-resolve/

**Comment by nielsmaerten** [comment]
Thanks for the article! I also received the canned response (claiming
actions were being reviewed for policy violations) from Google when I asked
them what was going on.

I agree with the article. An internal bug seems much more likely, given the
scope and number of actions affected.
Although if that's indeed the case, it looks like a monumental screw up on
their end, and we may never know what really happened.

But there's some good news as well:
I've been able to do a couple successful invocations from my Google home in
the past hours. It looks like the actions are coming online again.

Can anyone confirm this? Do you get a response to "Hey Google, talk to
Nightscout Status?"

**Comment by mistermintsgh** [comment]
Mine is working! 😃 Using both the standard "talk to Nightscout status" and my custom commands

**Comment by nielsmaerten** [comment]
That's great! All stats have returned to normal by now, so it looks like we're back everywhere.
Still no word from Google on what caused the outage, but here's to hoping it doesn't happen again.

Closing this issue
