### ISSUE TITLE
is service working?

### ISSUE THREAD

**Issue by dinizmauricio** [nielsmaerten/nightscout-assistant#98]
Hello,
I'm testing the integration, it works well for the website, but it doesn't work for the Google Home device . When I ask (ask Nightscout Status what my glucose is), I get the answer from some website.

I'm in Brazil.

If you can help me ...

**Comment by nielsmaerten** [comment]
Hi Mauricio,
Can you send an email to hello@niels.me? Please send from the same email address as the one you used to sign up. Then I'll be able to check the logs for your account.

When you ask Google Home to talk to Nightscout Status, what response do you get exactly?

**Comment by dinizmauricio** [comment]
Hello Niels,

I tried: talk to Nightscout Status
Google replied: I can’t help you with that.

When I try: Hey Google, ask Nightscout Status what my glucose is
I received: information from a website.

Thank's


Maurício Diniz
Email: m@uricio.net

**Comment by nielsmaerten** [comment]
Issues has been resolved through email. Closing this one.  

For anyone reading this afterwards: Support for Portuguese (Brazil) is still in bèta. You can email me to be added to the list of testers if you're interested.

**Comment by dinizmauricio** [comment]
Generally the programs have different files for Portuguese from Portugal
and Portuguese from Brazil.


I still need your help: I noticed that Google Home only works when the
"Send to device" button blue (see image). I can talk to Google Home for a
while, then it stops.


Em ter., 5 de mai. de 2020 às 07:12, Niels Maerten <notifications@github.com>
escreveu:
